### ISSUE TITLE
Bootstrapping your AWS account with Terraform

### ISSUE THREAD

**Issue by toan-hf** [HowDevOps/workshop-01#2]
as discussed with @locnh, i would like to briefly summarise what i think it makes sense for everyone before joining the first workshop-01. Because i think it will be missed if we don't mention about the TF strategy with AWS account before using TF to provision EKS - RDS and other stuffs like Workshop-01 will mention.

So this is what i am going to say

### AWS Account users
AWS Accounts start with a single root user. Access to this user needs to be carefully managed and following AWS best practices, the root user should not be used for day to day operations.

You may need to use the AWS console to set up an administrator user for yourself, get AWS Keys and configure awscli on your laptop first. Hopefully this is one of the few times we directly interact with the AWS Console as we try to codify all of our configuration to ensure reproducibility.

### AWS Naming conventions and billing tags
To keep track of our cloud resources and allow splitting costs by Tags, we should have a set of pre-defined resource tags consistently used across our cloud infrastructure. For this, we copied the Tags defined in the [cloudposse/terraform-null-label](https://github.com/cloudposse/terraform-null-label) module for all our resources, these tags seem to suit small startups like us.

Terraform state
Once you configured _awscli_, download Terraform. (i would suggest to download _tfenv_ instead of TF)
Because in the large environment, some of repos might still belong with old TF and other one might use newer version)
The difference of TF version will cause to a difference TF state and usually conflict TF state version leads to some unexpected issues. 

Terraform heavily relies on a so called state file. By default, the state file is kept locally within the project folder on your machine. For several team members to manage your cloud infrastructure, you will need to move the state file remotely and control access to it. Additionally, to keep TF configurations small and manageable as well as reduce blast radius for infrastructure changes, you need to split TF configurations across different state files referencing each other. Splitting state files is more portable when keeping them in a remote backend.

However, without any cloud infrastructure, you will have to start with a local state file until you have configured the necessary cloud resources.

We use Terraform itself to configure its own remote state storage. [As we are using AWS, we use S3 to store the state files and DynamoDb to manage locks and checksums](https://github.com/HowDevOps/workshop-01/blob/master/terraform/tf-mod-eks/terraform.tf#L3-L6). We also encrypt the state files with KMS as they will often contain sensitive information

_this is the variable.tf file_
```
variable "namespace" {
  description = "Namespace for terraform state resources"
}

variable "stage" {
  # We use:
  # - Prod for production
  # - Stage for staging
  # - Dev for development
  # - Svc for services (used across environments)
  description = "Stage for terraform state resources"
}

variable "name" {
  description = "Name for terraform state resources"
}

variable "aws_region" {
  description = "The AWS region to create things in."
  default     = "eu-west-1"
}
```

Next we define an S3 Bucket, a KMS Key for encryption and a DynamoDb table:
_so main.tf file_

```
provider "aws" {
  region = "${var.aws_region}"
}

module "howdevops_state_label" {
  source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=master"
  namespace  = "${var.namespace}"
  stage      = "${var.stage}"
  name       = "${var.name}"
}

resource "aws_s3_bucket" "tfstate" {
  bucket = "${module.howdevops_state_label.id}"
  acl    = "private"

  versioning {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }

  tags = "${module.howdevops_state_label.tags}"
}

resource "aws_kms_key" "master" {
  description             = "${module.howdevops_state_label.id} master encryption key for Terraform state"
  deletion_window_in_days = 10

  tags = "${module.howdevops_state_label.tags}"
}

# allows ease of use on cli
resource "aws_kms_alias" "secrets" {
  name          = "alias/${module.howdevops_state_label.id}-tfstate"
  target_key_id = "${aws_kms_key.master.key_id}"
}

resource "aws_dynamodb_table" "tfstate_lock" {
  name = "${module.howdevops_state_label.id}-lock"

  #http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ProvisionedThroughput.html
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "LockID"

  attribute {
    name = "LockID"
    type = "S"      # Attribute type, which must be a scalar type: (S)tring, (N)umber or (B)inary data
  }

  tags = "${module.howdevops_state_label.tags}"
}
```

Finally we can have _output.tf_ file 

```
output "bucket" {
  description = "The s3 bucket to use as Terraform Backend"
  value       = "${aws_s3_bucket.tfstate.id}"
}

output "lock_table" {
  description = "The DynamoDb table for s3 backend locking"
  value       = "${aws_dynamodb_table.tfstate_lock.id}"
}

output "region" {
  description = "The region used for remote state"
  value       = "${var.aws_region}"
}

output "kms_key_id" {
  description = "kms key for encryption of state"
  value       = "${aws_kms_key.master.key_id}"
}
```

Finally, to use this in our future Terraform workshop, we just need to provide the backend configuration in the terraform provider like @locnh has mentioned [here](https://github.com/HowDevOps/workshop-01/blob/master/terraform/tf-mod-eks/terraform.tf)

After you provisioned those 3 resources (S3 - KMS - DynamoDB) then you can go ahead with the 

Disclaimer : I recommend to use KMS but it's totally up to you (KMS is an optional)

Thanks !

**Comment by onimsha** [comment]
I think we should not over-complicating this workshop. The point of a workshop is "getting something up and running", so we should leave most of the auxiliary setup with default settings.  We really should just use local tfstate rather than using s3 + dynamodb , which we could introduce them in another workshop. Remember remote state is ONLY for team collaboration, which is not necessary in a workshop.

**Comment by toan-hf** [comment]
totally agree. So @locnh  just need to remove few lines like we mentioned earlier. i think all my things above should not be mentioned.

**Comment by locnh** [comment]
Hi @onimsha @toan-hf 
Thanks for your comments, but they're there for a purpose.

Closed.

**Comment by onimsha** [comment]
Would you care to explain what's the purpose of that ?
